api_platform:
    title: Healthcare API
    description: API for managing healthcare data
    version: 1.0.0
    defaults:
        route_prefix: /api
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
